version: "3.8"
services:
  fastapi:
    build: .
    container_name: fastapi_kuber
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/app/src
    ports:
      - "8001:8000"
    depends_on:
      - redis_kuber
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://kjune0922:dlrudalswns2@postgres_kuber:5432/kuber_db
      - CELERY_BROKER_URL=redis://redis_kuber:6379/0
      - CELERY_RESULT_BACKEND=redis://redis_kuber:6379/0

  worker:
    build: .
    container_name: celery_kuber
    command: celery -A src.celery_app worker --beat --loglevel=info
    volumes:
      - ./src:/app/src
    depends_on:
      - redis_kuber
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://kjune0922:dlrudalswns2@postgres_kuber:5432/kuber_db
      - CELERY_BROKER_URL=redis://redis_kuber:6379/0
      - CELERY_RESULT_BACKEND=redis://redis_kuber:6379/0

  redis_kuber:
    image: redis:6
    container_name: redis_kuber
    ports:
      - "6380:6379"

  db:
    image: postgres:15
    container_name: postgres_kuber
    environment:
      POSTGRES_USER: kjune0922
      POSTGRES_PASSWORD: dlrudalswns2
      POSTGRES_DB: kuber_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
    depends_on:
      - db

volumes:
  pgdata: {}
